# Sequence below was given by rosalind to test if code would produce correct output 
# Given: A DNA string s of length at most 1000 nt.
seq = "TAAGTGGAGTGGGGCAACCACTCATCCGCCCTAATCTTCAACTACGTAAAATCACCTCATTACCATCAGGTTAGCTGGTACTCCTAGTGTAAGTTATAACTAGGTCTTTACCTAAAAGAGGGAGCTATTTGTACACCGAATGTTGACTGTGAGCCACACTACGTATGCCGCGGAGCGAAGCTAATTTGCCACTCCCTTATCATTGCGTCACGCACCTGCTTTAGTGCGCAATAACCCAAACGCACAGGACGAGGAACAGCCCTACGTTTTACACCTCTCTCATAAAACGATAGACAGTTCCGCAGTCACTATGCTATAGATCAGGCCTGCTTTGCTTTTATGCCGTTGATAAAGTAGTTGGGCCCAATCCTAGTATACACGATGACGGCCTGTGCCACTAGCGGGGTAAAAGCTGGCGAGCTGCTCATAATCGAGGCAGTCAGAGAGTAAACGCGTGCCAAATAGTAGTCTGTACACAACGGCCAGAGCCCGGCCCTGTCCCACCGCCTGCCTTCAAAATTCACATTTAGGAATGAGATATGATTACTTACTGAGAAACTGAGTCATATACACGGCACTGCGTCGAACCCATCGGTGATTGTTCTCCTGGTTTACTGGAAACCGTCCAAGCGATATCCAGTACCAAAGGGTGCGGGCGCCGTCTGCACTATCTCGGAAATCTGGATCGTTAATTGAAGCAATGCAGGCCGATACACTCGTGGCGACTCCCCTACCGCGAAGGCCTGAGCCATTGGGGTCGCATGCAGTGGGACTCAAGCCGTGGTCACCCGTAGAGCAGCGGAACTAAGTCTTACTCCTCATAACTTGGGAGGGTATGCACTTCAATCCAACGGGCTTATTCAAGTGACGCTCTCTCGTAGGCGTGCAAGACTTACTCTTAGGTCTGTCCTCTAGGGAGCTCCCACTTTTTGGCGAACAGATGTACTACATCAGCTCACGCCCGCCACCATCGTACACCA"

def countNucFrequency(seq):
    # Creating empty dictionary with each possible nucleotide
    tmpFreqDict = {"A": 0, "C": 0, "G": 0, "T": 0}
    # For loop which loops through each nucleotide in the sequence, finds the mathcing nucleotide in the dictionary and tallies them up
    for nuc in seq:
        tmpFreqDict[nuc] += 1
    return tmpFreqDict

result = countNucFrequency(seq)
# Formatting answer the way rosalind would accept it
# Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in.
print(' '.join([str(val) for key, val in result.items()]))
